name: Deploy-flask-app

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print test
        run: echo "start test"

  deploy:
    runs-on: self-hosted
    steps:
     - name: Print deploy
       run: echo "start deploy"
